/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Color;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Johan
 */
public class confirmRegPanel extends javax.swing.JPanel {

    private PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    private IMatDataHandler userData = IMatDataHandler.getInstance();

    /**
     * Creates new form confirmRegPanel
     */
    public confirmRegPanel() {
        initComponents();
        straightToPayLabel.setBackground(Color.lightGray);
        straightToPayLabel.setVisible(false);
        straightToPayLabel.setEnabled(false);
        this.setBackground(IMatColors.getpanelBackgroundNormal());
    }
    
    public void enableSTPLabel(boolean b) {
        straightToPayLabel.setVisible(b);
        straightToPayLabel.setEnabled(b);
    }
    
    public void addObserver(PropertyChangeListener observer){
        pcs.addPropertyChangeListener(observer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imageLabel1 = new imat.ImageLabel();
        straightToPayLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namnLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        emailblabla = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Välkommen till iMat!");

        jLabel2.setText("Du kan nu börja handla!");

        jLabel3.setText("Om du vill ändra dina uppgifter kan du göra detta via din profilsida.");

        imageLabel1.setText("imageLabel1");
        imageLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabel1MouseClicked(evt);
            }
        });

        straightToPayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        straightToPayLabel.setText("Fortsätt direkt till kassan");
        straightToPayLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        straightToPayLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                straightToPayLabelMouseMoved(evt);
            }
        });
        straightToPayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                straightToPayLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                straightToPayLabelMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Namn:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Adress:");

        namnLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namnLabel.setText("Namn:");

        adressLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adressLabel.setText("Adress:");

        emailblabla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emailblabla.setText("Email:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emailLabel.setText("Adress:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(straightToPayLabel)
                            .addGap(117, 117, 117)
                            .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(451, 451, 451)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(emailblabla))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(495, 495, 495))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namnLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adressLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailblabla)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(straightToPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setRegInfo() {
        String fornamn = userData.getCustomer().getFirstName();
        String efternamn = userData.getCustomer().getLastName();
        String adress = userData.getCustomer().getAddress();
        String postNr = userData.getCustomer().getPostCode();
        String stad = userData.getCustomer().getPostAddress();
        String mail = userData.getCustomer().getEmail();
        namnLabel.setText(fornamn + " " + efternamn);
        adressLabel.setText(adress + " - " + postNr + " " + stad);
        emailLabel.setText(mail);
    }
    
    private void imageLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel1MouseClicked
        pcs.firePropertyChange("ToProducts", 0, 1);
    }//GEN-LAST:event_imageLabel1MouseClicked

    private void straightToPayLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_straightToPayLabelMouseMoved
        straightToPayLabel.setBackground(Color.gray);
    }//GEN-LAST:event_straightToPayLabelMouseMoved

    private void straightToPayLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_straightToPayLabelMouseExited
        straightToPayLabel.setBackground(Color.lightGray);
    }//GEN-LAST:event_straightToPayLabelMouseExited

    private void straightToPayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_straightToPayLabelMouseClicked
        pcs.firePropertyChange("ToCheckout", 0, 1);
    }//GEN-LAST:event_straightToPayLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailblabla;
    private imat.ImageLabel imageLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel namnLabel;
    private javax.swing.JLabel straightToPayLabel;
    // End of variables declaration//GEN-END:variables
}
