/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Cursor;
import java.awt.Dimension;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Johan
 */
public class HomeProductCard extends javax.swing.JPanel {
    
    private IMatDataHandler userData = IMatDataHandler.getInstance();
    private Product item;
    private final Dimension size = new Dimension(251, 251);
    /**
     * Creates new form HomeProductCard
     */
    public HomeProductCard(Product p) {
        initComponents();
        item = p;
        jLabelEnhet.setText(p.getUnitSuffix());
        jLabelNamn.setText(p.getName());
        jLabelPrisPerEnhet.setText(p.getPrice() + " kr/" + p.getUnitSuffix());
        produktBild.setIcon(userData.getImageIcon(p, size));
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNamn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrisPerEnhet = new javax.swing.JLabel();
        imageLabelMinus = new imat.ImageLabel("checkoutMinusButton.png");
        imageLabelPlus = new imat.ImageLabel("checkoutPlusButton.png");
        jTextFieldAntal = new javax.swing.JTextField();
        jLabelEnhet = new javax.swing.JLabel();
        imageLabelLaggTill = new imat.ImageLabel("addToCartButton.png");
        produktBild = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNamn.setText("<Produktnamn>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Just nu endast");

        jLabelPrisPerEnhet.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrisPerEnhet.setText("X kr/Unit");

        imageLabelMinus.setText("imageLabel2");
        imageLabelMinus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelMinusMouseMoved(evt);
            }
        });
        imageLabelMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMinusMouseClicked(evt);
            }
        });

        imageLabelPlus.setText("imageLabel2");
        imageLabelPlus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelPlusMouseMoved(evt);
            }
        });
        imageLabelPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelPlusMouseClicked(evt);
            }
        });

        jTextFieldAntal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldAntal.setText("1");
        jTextFieldAntal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAntalKeyTyped(evt);
            }
        });

        jLabelEnhet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEnhet.setText("Unit");

        imageLabelLaggTill.setText("imageLabel4");
        imageLabelLaggTill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelLaggTillMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produktBild, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 194, Short.MAX_VALUE)
                        .addComponent(imageLabelLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelNamn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelEnhet))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(imageLabelMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(imageLabelPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelPrisPerEnhet))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPrisPerEnhet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imageLabelMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imageLabelPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEnhet)
                                    .addComponent(jTextFieldAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addComponent(imageLabelLaggTill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(produktBild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMinusMouseClicked
        if (Integer.parseInt(jTextFieldAntal.getText()) > 1){
            jTextFieldAntal.setText(Integer.parseInt(jTextFieldAntal.getText()) - 1 + "");
        } else {
            jTextFieldAntal.setText(99 + "");
        }
    }//GEN-LAST:event_imageLabelMinusMouseClicked

    private void imageLabelPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelPlusMouseClicked
        if (Integer.parseInt(jTextFieldAntal.getText()) < 99){
            jTextFieldAntal.setText(Integer.parseInt(jTextFieldAntal.getText()) + 1 + "");
        } else {
            jTextFieldAntal.setText(1 + "");
        }
    }//GEN-LAST:event_imageLabelPlusMouseClicked

    private void imageLabelLaggTillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelLaggTillMouseClicked
        userData.getShoppingCart().addProduct(item, Integer.parseInt(jTextFieldAntal.getText()));
    }//GEN-LAST:event_imageLabelLaggTillMouseClicked

    private void imageLabelMinusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMinusMouseMoved
        imageLabelMinus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_imageLabelMinusMouseMoved

    private void imageLabelPlusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelPlusMouseMoved
        imageLabelPlus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_imageLabelPlusMouseMoved

    private void jTextFieldAntalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAntalKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9') || jTextFieldAntal.getText().length() > 1)
                && (caracter != '\b')) {
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextFieldAntalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.ImageLabel imageLabelLaggTill;
    private imat.ImageLabel imageLabelMinus;
    private imat.ImageLabel imageLabelPlus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEnhet;
    private javax.swing.JLabel jLabelNamn;
    private javax.swing.JLabel jLabelPrisPerEnhet;
    private javax.swing.JTextField jTextFieldAntal;
    private javax.swing.JLabel produktBild;
    // End of variables declaration//GEN-END:variables
}
