/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author jonathan
 */
public class ProductCard extends javax.swing.JPanel {
    
    private final IMatDataHandler data = IMatDataHandler.getInstance();
    
    private final Dimension IMGDIMENSION = new Dimension(50,50);
    
    private final Product p;

    /**
     * Creates new form ProductCard
     */
    public ProductCard() {
        initComponents();
        this.p = null;
    }
    
    public ProductCard(Product p) {
        initComponents();
        this.p=p;
        productImage.setIcon(data.getImageIcon(p,IMGDIMENSION));
        productUnitsLabel.setText(p.getUnitSuffix());
        productNameLabel.setText(p.getName());
        productPriceLabel.setText(p.getPrice() + " " + p.getUnit());
        this.setBackground(IMatColors.getpanelBackgroundDark());
        this.setVisible(true);
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImage = new javax.swing.JLabel();
        addToCartButton = new imat.ImageLabel("addToCartButton.png");
        productUnitsLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        addToShoppingListButton = new imat.ImageLabel("addToShoppingListButton.png");
        favoriteButton = new imat.ImageLabel("unmarkedFavButton.png", "markedFavButton.png");
        nbrOfProductsTF = new javax.swing.JTextField();
        increaseLabel = new imat.ImageLabel("checkoutPlusButton.png");
        decreaseLabel = new imat.ImageLabel("checkoutMinusButton.png");

        setForeground(IMatColors.getpanelBackgroundDark());
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(210, 227));
        setMinimumSize(new java.awt.Dimension(210, 227));
        setPreferredSize(new java.awt.Dimension(210, 227));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        productImage.setMaximumSize(new java.awt.Dimension(60, 60));
        productImage.setMinimumSize(new java.awt.Dimension(60, 60));
        productImage.setPreferredSize(new java.awt.Dimension(60, 60));
        productImage.setRequestFocusEnabled(false);

        addToCartButton.setText("imageLabel1");
        addToCartButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseMoved(evt);
            }
        });
        addToCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseClicked(evt);
            }
        });

        productUnitsLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        productUnitsLabel.setText("kg");

        productNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        productNameLabel.setText("ProductName");

        productPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        productPriceLabel.setText("Price");

        addToShoppingListButton.setText("imageLabel1");
        addToShoppingListButton.setToolTipText("");
        addToShoppingListButton.setMaximumSize(new java.awt.Dimension(40, 40));
        addToShoppingListButton.setMinimumSize(new java.awt.Dimension(40, 40));
        addToShoppingListButton.setPreferredSize(new java.awt.Dimension(40, 40));
        addToShoppingListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToShoppingListButtonMouseClicked(evt);
            }
        });
        addToShoppingListButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addToShoppingListButtonMouseMoved(evt);
            }
        });

        favoriteButton.setText("imageLabel1");
        favoriteButton.setMaximumSize(new java.awt.Dimension(30, 30));
        favoriteButton.setMinimumSize(new java.awt.Dimension(30, 30));
        favoriteButton.setPreferredSize(new java.awt.Dimension(30, 30));
        favoriteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favoriteButtonMouseClicked(evt);
            }
        });

        nbrOfProductsTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nbrOfProductsTF.setText("1");
        nbrOfProductsTF.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nbrOfProductsTFMouseMoved(evt);
            }
        });
        nbrOfProductsTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nbrOfProductsTFMouseExited(evt);
            }
        });

        increaseLabel.setText("imageLabel1");
        increaseLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                increaseLabelMouseMoved(evt);
            }
        });
        increaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                increaseLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                increaseLabelMouseExited(evt);
            }
        });

        decreaseLabel.setText("imageLabel1");
        decreaseLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                decreaseLabelMouseMoved(evt);
            }
        });
        decreaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decreaseLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decreaseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(favoriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(decreaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(increaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nbrOfProductsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productUnitsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addToShoppingListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decreaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(increaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbrOfProductsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productUnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToShoppingListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO go to the specific product panel for THIS product
    }//GEN-LAST:event_formMouseClicked

    private void addToShoppingListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToShoppingListButtonMouseClicked
        // TODO Add the product to the shopping lists.
    }//GEN-LAST:event_addToShoppingListButtonMouseClicked

    private void addToCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseClicked
        // Add the product to the shoppingCart with the amount of products
        // that is specified by nbrOfProductsTF.
        if (this.controlNbrOfProductsTF()) {
            data.getShoppingCart().addProduct(p, Integer.parseInt(nbrOfProductsTF.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Mängd mäts i siffror bryshan");
        }
    }//GEN-LAST:event_addToCartButtonMouseClicked

    private void favoriteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteButtonMouseClicked
        
        if(data.isFavorite(p)) {
             // Om produkten redan är favoritmarkerad -> ta bort favorit markeringen
            data.removeFavorite(p);
            favoriteButton.imageNormal();
        } else {
            //Om produkten inte är favoritmarkerad -> markera den som favorit
            data.addFavorite(p);
            favoriteButton.imageHover();
        }
    }//GEN-LAST:event_favoriteButtonMouseClicked

    private boolean controlNbrOfProductsTF() {
        
        for (int i = 0; i < nbrOfProductsTF.getText().length(); i++) {
            char a = nbrOfProductsTF.getText().charAt(i);
            if (a != '0' && a != '1' && a != '2' && a != '3' && a != '4' && a != '5' && a != '6' && a != '7' && a != '8' && a != '9') {
                return false;
            }
        }
        return true;
    }
    
    private void incProducts() {
        int products;
        if (this.controlNbrOfProductsTF()) {
            products = Integer.parseInt(nbrOfProductsTF.getText());
            products++;
            if (products == 100) {
               products = 1;
            }
        } else {
            products = 1;
        }
         nbrOfProductsTF.setText(Integer.toString(products));
    }
    
    private void decProducts() {
        int products;
        if (this.controlNbrOfProductsTF()) {
            products = Integer.parseInt(nbrOfProductsTF.getText());
            products--;
            if (products == 0) {
                products = 99;
            }
        } else {
            products = 1;
        }
        nbrOfProductsTF.setText(Integer.toString(products));
    }
    
    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
    }//GEN-LAST:event_formMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(IMatColors.getpanelBackgroundDark());
    }//GEN-LAST:event_formMouseExited

    private void addToShoppingListButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToShoppingListButtonMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
    }//GEN-LAST:event_addToShoppingListButtonMouseMoved

    private void addToCartButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
    }//GEN-LAST:event_addToCartButtonMouseMoved

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(IMatColors.getpanelBackgroundLight());
    }//GEN-LAST:event_formMouseEntered

    private void increaseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseLabelMouseClicked
        this.incProducts();
    }//GEN-LAST:event_increaseLabelMouseClicked

    private void decreaseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseLabelMouseClicked
        this.decProducts();
    }//GEN-LAST:event_decreaseLabelMouseClicked

    private void increaseLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseLabelMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
        increaseLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_increaseLabelMouseMoved

    private void increaseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseLabelMouseExited
        this.setBackground(IMatColors.getpanelBackgroundDark());
    }//GEN-LAST:event_increaseLabelMouseExited

    private void decreaseLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseLabelMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
        decreaseLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_decreaseLabelMouseMoved

    private void decreaseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseLabelMouseExited
        this.setBackground(IMatColors.getpanelBackgroundDark());
    }//GEN-LAST:event_decreaseLabelMouseExited

    private void nbrOfProductsTFMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nbrOfProductsTFMouseMoved
        this.setBackground(IMatColors.getpanelBackgroundLight());
    }//GEN-LAST:event_nbrOfProductsTFMouseMoved

    private void nbrOfProductsTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nbrOfProductsTFMouseExited
        this.setBackground(IMatColors.getpanelBackgroundDark());
    }//GEN-LAST:event_nbrOfProductsTFMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.ImageLabel addToCartButton;
    private imat.ImageLabel addToShoppingListButton;
    private imat.ImageLabel decreaseLabel;
    private imat.ImageLabel favoriteButton;
    private imat.ImageLabel increaseLabel;
    private javax.swing.JTextField nbrOfProductsTF;
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JLabel productUnitsLabel;
    // End of variables declaration//GEN-END:variables
}