/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import se.chalmers.ait.dat215.project.Product;
import javax.swing.JPanel;

/**
 *
 * @author jonathan
 */
public class SearchResultPanel extends JPanel {

    /**
     * Creates new form SearchResultPanel
     */
    
    private static SearchResultPanel test = new SearchResultPanel("hej");
    
    public SearchResultPanel() {
        initComponents();
    }
    
    private SearchResultPanel(String s) {
        initComponents();
        this.test = this;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaOfSearchResult = new javax.swing.JScrollPane();
        searchResultCardContainer = new javax.swing.JPanel();

        areaOfSearchResult.setMaximumSize(new java.awt.Dimension(734, 281));
        areaOfSearchResult.setMinimumSize(new java.awt.Dimension(734, 281));
        areaOfSearchResult.setPreferredSize(new java.awt.Dimension(734, 281));

        searchResultCardContainer.setMaximumSize(new java.awt.Dimension(734, 281));
        searchResultCardContainer.setMinimumSize(new java.awt.Dimension(734, 281));
        searchResultCardContainer.setPreferredSize(new java.awt.Dimension(734, 281));

        javax.swing.GroupLayout searchResultCardContainerLayout = new javax.swing.GroupLayout(searchResultCardContainer);
        searchResultCardContainer.setLayout(searchResultCardContainerLayout);
        searchResultCardContainerLayout.setHorizontalGroup(
            searchResultCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        searchResultCardContainerLayout.setVerticalGroup(
            searchResultCardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        areaOfSearchResult.setViewportView(searchResultCardContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaOfSearchResult, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areaOfSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        areaOfSearchResult.getVerticalScrollBar().setUnitIncrement(16);
    }// </editor-fold>//GEN-END:initComponents

    public void displayResults(List<Product> results) {
        searchResultCardContainer.removeAll();
        revalidate();
        int nbrOfResults = results.size();
        
        // Räkna ut antalet rader för layouten av areaOfSearchResult
        int nbrOfRows = nbrOfResults/2;
        searchResultCardContainer.setLayout(new GridLayout(nbrOfRows,2));
        
        int height = nbrOfRows*200 + (nbrOfRows-2)*10 + 20;
        int width = 2*200 + 30;
        
        Dimension d = new Dimension(width,height);
        
        searchResultCardContainer.setPreferredSize(d);
        searchResultCardContainer.setMaximumSize(d);
        searchResultCardContainer.setMinimumSize(d);
        searchResultCardContainer.setSize(d);
        
        areaOfSearchResult.setPreferredSize(d);
        areaOfSearchResult.setMaximumSize(d);
        areaOfSearchResult.setMinimumSize(d);
        areaOfSearchResult.setSize(d);
        
        ArrayList<ProductCard> pc = new ArrayList(results.size());
        
        // Skapar ProductCard för alla sökresultat
        for(int i=0; i<nbrOfResults; i++) {
            pc.add(new ProductCard(results.get(i)));
            pc.get(i).setVisible(true);
        }
        
        for(int i=0; i<nbrOfResults; i++) {
            searchResultCardContainer.add(pc.get(i), i);
        }
        
        searchResultCardContainer.repaint();
        searchResultCardContainer.revalidate();
        areaOfSearchResult.repaint();
        areaOfSearchResult.revalidate();
        repaint();
        revalidate();
    }
    
    public static SearchResultPanel getInstance() {
        return test;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane areaOfSearchResult;
    private javax.swing.JPanel searchResultCardContainer;
    // End of variables declaration//GEN-END:variables
    
}
