/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.GridLayout;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.List;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;
import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import se.chalmers.ait.dat215.project.CartEvent;
import se.chalmers.ait.dat215.project.ShoppingCartListener;


/**
 *
 * @author Johan
 */
public class shoppingCartPanel extends javax.swing.JPanel implements ShoppingCartListener {

    private PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    private IMatDataHandler userData = IMatDataHandler.getInstance();
    
    /**
     * Creates new form shoppingCartPanel
     */
    public shoppingCartPanel() {
        initComponents();
        jPanel1.setMaximumSize(new Dimension(305, 406));
        jPanel1.setLayout(new GridLayout(10, 1));
        
    }
    
    public void addObserver(PropertyChangeListener observer){
        pcs.addPropertyChangeListener(observer);
        userData.getShoppingCart().addShoppingCartListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageLabel1 = new imat.ImageLabel("kundvagn.png");
        imageLabelEmptyCart = new imat.ImageLabel("emptyShoppingCartButton.png");
        imageLabelToCheckout = new imat.ImageLabel("toCheckoutButton.png");
        jLabel2 = new javax.swing.JLabel();
        jLabelAntalProdukter = new javax.swing.JLabel();
        jLabelTotalKostnad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(337, 604));
        setMinimumSize(new java.awt.Dimension(337, 604));
        setPreferredSize(new java.awt.Dimension(337, 604));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Kundvagn");

        imageLabel1.setText("imageLabel1");

        imageLabelEmptyCart.setText("imageLabel2");
        imageLabelEmptyCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelEmptyCartMouseClicked(evt);
            }
        });

        imageLabelToCheckout.setBackground(new java.awt.Color(255, 255, 255));
        imageLabelToCheckout.setText("imageLabel3");
        imageLabelToCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelToCheckoutMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Totalt:");

        jLabelAntalProdukter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAntalProdukter.setText("X produkter");

        jLabelTotalKostnad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTotalKostnad.setText("X kr");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(imageLabelEmptyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalKostnad)
                    .addComponent(jLabelAntalProdukter)
                    .addComponent(imageLabelToCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAntalProdukter)
                        .addGap(7, 7, 7)
                        .addComponent(jLabelTotalKostnad))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabelToCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabelEmptyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelToCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelToCheckoutMouseClicked
        if (userData.isCustomerComplete()) {
            pcs.firePropertyChange("ToCheckout", 0 , 1);
        } else {
            pcs.firePropertyChange("ToFirstRegPanel", 0, 1);
        }
    }//GEN-LAST:event_imageLabelToCheckoutMouseClicked

    private void imageLabelEmptyCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelEmptyCartMouseClicked
        userData.getShoppingCart().clear();
        jPanel1.removeAll();
    }//GEN-LAST:event_imageLabelEmptyCartMouseClicked
    
    
    List<Product> avp = new ArrayList<>();
    
    @Override
    public void shoppingCartChanged(CartEvent evt){
        jPanel1.removeAll();
        if(!avp.contains(evt.getShoppingItem().getProduct())){
          
            if (userData.getShoppingCart().getItems().size() > 0){    
                
                int visibleItems = 0;
                avp.clear();

                for (int i = userData.getShoppingCart().getItems().size() -1; i >= 0 ; i--) {

                    ShoppingItem si = userData.getShoppingCart().getItems().get(i);

                    if (visibleItems < 10 && si != null && !avp.contains(si.getProduct())) {
                        int antal = (int)si.getAmount();

                        for (int k = i-1; k >= 0; k--){
                            if (userData.getShoppingCart().getItems().get(k).getProduct().getName().equals(si.getProduct().getName())){
                                antal += (int)userData.getShoppingCart().getItems().get(k).getAmount();
                            }
                        }
                        jPanel1.add(new shoppingCartProductPanel(antal, si.getProduct()));
                        
                        avp.add(si.getProduct());
                        visibleItems++;
                    }

                }
            }
        } else {
            
            for (Product pr: avp){
                int antalPr = 0;
                for (int i = 0; i < userData.getShoppingCart().getItems().size(); i++){
                    System.out.println("1");
                    if (userData.getShoppingCart().getItems().get(i).getProduct().equals(pr)){
                        antalPr += (int)userData.getShoppingCart().getItems().get(i).getAmount();
                        System.out.println("2");
                    }  
                }
                if (antalPr > 0){
                    jPanel1.add(new shoppingCartProductPanel(antalPr, pr));
                }
            }
            
        }
        int totAntalProdukter = 0;
            
            for (int i = 0; i < userData.getShoppingCart().getItems().size();i++){
                totAntalProdukter += (int)userData.getShoppingCart().getItems().get(i).getAmount();
            }
            
            jLabelAntalProdukter.setText(totAntalProdukter + " produkter");
            jLabelTotalKostnad.setText(userData.getShoppingCart().getTotal() + " kr");
        
        revalidate();
        repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.ImageLabel imageLabel1;
    private imat.ImageLabel imageLabelEmptyCart;
    private imat.ImageLabel imageLabelToCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAntalProdukter;
    private javax.swing.JLabel jLabelTotalKostnad;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
