/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

/**
 *
 * @author Johan
 */
public class shoppingCartProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form shoppingCartProductPanel
     */
    public shoppingCartProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAntal = new javax.swing.JLabel();
        jLabelAntalStEllerKg = new javax.swing.JLabel();
        jLabelProduktnamn = new javax.swing.JLabel();
        jLabelPris = new javax.swing.JLabel();
        jLabelPerStEllerKg = new javax.swing.JLabel();

        jLabelAntal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAntal.setText("X");

        jLabelAntalStEllerKg.setText("st");

        jLabelProduktnamn.setText("<produktnamn>");

        jLabelPris.setText("x kr");

        jLabelPerStEllerKg.setText("/st");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelAntal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAntalStEllerKg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProduktnamn)
                .addGap(18, 18, 18)
                .addComponent(jLabelPris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPerStEllerKg)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAntal)
                    .addComponent(jLabelAntalStEllerKg)
                    .addComponent(jLabelProduktnamn)
                    .addComponent(jLabelPris)
                    .addComponent(jLabelPerStEllerKg))
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAntal;
    private javax.swing.JLabel jLabelAntalStEllerKg;
    private javax.swing.JLabel jLabelPerStEllerKg;
    private javax.swing.JLabel jLabelPris;
    private javax.swing.JLabel jLabelProduktnamn;
    // End of variables declaration//GEN-END:variables
}
