/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.util.List;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Johan
 */
public class shoppingCartProductPanel extends javax.swing.JPanel {

    private IMatDataHandler userData = IMatDataHandler.getInstance();
    private Product p;
    private int antal;
    /**
     * Creates new form shoppingCartProductPanel
     */
    public shoppingCartProductPanel() {
        initComponents();
    }
    
    public shoppingCartProductPanel(int antal, Product p){
        initComponents();
        this.p = p;
        this.antal = antal;
        jLabelAntal.setText("" + antal);
        jLabelAntalStEllerKg.setText(p.getUnitSuffix());
        jLabelProduktnamn.setText(p.getName());
        jLabelPris.setText(p.getPrice() + " kr/" + p.getUnitSuffix());
    }
    
    /**public shoppingCartProductPanel(int antal, String stKgForp, String produktnamn, double pris) {
        initComponents();
        jLabelAntal.setText("" + antal);
        jLabelAntalStEllerKg.setText(stKgForp);
        jLabelProduktnamn.setText(produktnamn);
        jLabelPris.setText(pris + " kr/" + stKgForp);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAntal = new javax.swing.JLabel();
        jLabelAntalStEllerKg = new javax.swing.JLabel();
        jLabelProduktnamn = new javax.swing.JLabel();
        jLabelPris = new javax.swing.JLabel();
        imageLabelTaBort = new imat.ImageLabel("deleteItemCheckoutButton.png");
        imageLabelMinska = new imat.ImageLabel("checkoutMinusButton.png");
        imageLabelÖka = new imat.ImageLabel("checkoutPlusButton.png");

        jLabelAntal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAntal.setText("X");

        jLabelAntalStEllerKg.setText("st");

        jLabelProduktnamn.setText("<produktnamn>");

        jLabelPris.setText("x kr/st");

        imageLabelTaBort.setText("imageLabel1");
        imageLabelTaBort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelTaBortMouseClicked(evt);
            }
        });

        imageLabelMinska.setText("imageLabel1");
        imageLabelMinska.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMinskaMouseClicked(evt);
            }
        });

        imageLabelÖka.setText("imageLabel1");
        imageLabelÖka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelÖkaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabelMinska, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(imageLabelÖka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabelAntal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAntalStEllerKg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabelProduktnamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabelTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabelMinska, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(imageLabelÖka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(imageLabelTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelPris)
                .addComponent(jLabelProduktnamn)
                .addComponent(jLabelAntalStEllerKg))
            .addComponent(jLabelAntal)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelTaBortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelTaBortMouseClicked
        List<ShoppingItem> items = userData.getShoppingCart().getItems();
        
        for (int i = items.size() - 1; i >= 0; i--){
            if (items.get(i).getProduct().getName().equals(this.jLabelProduktnamn.getText())){
                userData.getShoppingCart().removeItem(i);
                userData.getShoppingCart().fireShoppingCartChanged(null, true);
            }
        }
        
    }//GEN-LAST:event_imageLabelTaBortMouseClicked

    private void imageLabelÖkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelÖkaMouseClicked
        userData.getShoppingCart().addProduct(p);
        userData.getShoppingCart().fireShoppingCartChanged(null, true);
    }//GEN-LAST:event_imageLabelÖkaMouseClicked

    private void imageLabelMinskaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMinskaMouseClicked
        antal--;
        List<ShoppingItem> items = userData.getShoppingCart().getItems();
        
        for (int i = items.size() - 1; i >= 0; i--){
            if (items.get(i).getProduct().getName().equals(this.jLabelProduktnamn.getText())){
                userData.getShoppingCart().removeItem(i);
            }
        }
        if (antal > 0){
            userData.getShoppingCart().addProduct(p, antal);
        }
        userData.getShoppingCart().fireShoppingCartChanged(null, true);
    }//GEN-LAST:event_imageLabelMinskaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.ImageLabel imageLabelMinska;
    private imat.ImageLabel imageLabelTaBort;
    private imat.ImageLabel imageLabelÖka;
    private javax.swing.JLabel jLabelAntal;
    private javax.swing.JLabel jLabelAntalStEllerKg;
    private javax.swing.JLabel jLabelPris;
    private javax.swing.JLabel jLabelProduktnamn;
    // End of variables declaration//GEN-END:variables
}
