/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Color;
import java.awt.Cursor;
import java.util.List;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Johan
 */
public class shoppingCartProductPanel extends javax.swing.JPanel {

    private IMatDataHandler userData = IMatDataHandler.getInstance();
    private Product p;
    private int antal;
    /**
     * Creates new form shoppingCartProductPanel
     */
    public shoppingCartProductPanel() {
        initComponents();
    }
    
    public shoppingCartProductPanel(int antal, Product p){
        initComponents();
        this.p = p;
        this.antal = antal;
        this.setBackground(Color.lightGray);
        jLabelAntal.setText(antal + " " + p.getUnitSuffix());
        jLabelProduktnamn.setText(p.getName());
        jLabelPris.setText(p.getPrice() + " kr/" + p.getUnitSuffix());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAntal = new javax.swing.JLabel();
        jLabelProduktnamn = new javax.swing.JLabel();
        jLabelPris = new javax.swing.JLabel();
        imageLabelTaBort = new imat.ImageLabel("deleteItemCheckoutButton.png");
        imageLabelMinska = new imat.ImageLabel("checkoutMinusButton.png");
        imageLabelÖka = new imat.ImageLabel("checkoutPlusButton.png");

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(282, 25));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jLabelAntal.setText("Xst");

        jLabelProduktnamn.setText("<produktnamn>");

        jLabelPris.setText("x kr/st");

        imageLabelTaBort.setText("imageLabel1");
        imageLabelTaBort.setToolTipText("Ta bort alla varor av denna sort");
        imageLabelTaBort.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelTaBortMouseMoved(evt);
            }
        });
        imageLabelTaBort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelTaBortMouseClicked(evt);
            }
        });

        imageLabelMinska.setText("imageLabel1");
        imageLabelMinska.setToolTipText("Ta bort en vara av denna sort");
        imageLabelMinska.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelMinskaMouseMoved(evt);
            }
        });
        imageLabelMinska.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMinskaMouseClicked(evt);
            }
        });

        imageLabelÖka.setText("imageLabel1");
        imageLabelÖka.setToolTipText("Lägg till en vara av denna sort");
        imageLabelÖka.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imageLabelÖkaMouseMoved(evt);
            }
        });
        imageLabelÖka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelÖkaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabelMinska, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(imageLabelÖka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAntal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProduktnamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(imageLabelTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabelMinska, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(imageLabelÖka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(imageLabelTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelPris)
                .addComponent(jLabelProduktnamn)
                .addComponent(jLabelAntal))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelTaBortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelTaBortMouseClicked
        List<ShoppingItem> items = userData.getShoppingCart().getItems();
        
        for (int i = items.size() - 1; i >= 0; i--){
            if (items.get(i).getProduct().getName().equals(this.jLabelProduktnamn.getText())){
                userData.getShoppingCart().removeItem(i);
            }
        }
        
    }//GEN-LAST:event_imageLabelTaBortMouseClicked

    private void imageLabelÖkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelÖkaMouseClicked
        userData.getShoppingCart().addProduct(p);
    }//GEN-LAST:event_imageLabelÖkaMouseClicked

    private void imageLabelMinskaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMinskaMouseClicked
        antal--;
        List<ShoppingItem> items = userData.getShoppingCart().getItems();
        
        for (int i = items.size() - 1; i >= 0; i--){
            if (items.get(i).getProduct().getName().equals(this.jLabelProduktnamn.getText())){
                userData.getShoppingCart().removeItem(i);
            }
        }
        if (antal > 0){
            userData.getShoppingCart().addProduct(p, antal);
        }
    }//GEN-LAST:event_imageLabelMinskaMouseClicked

    private void imageLabelTaBortMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelTaBortMouseMoved
        imageLabelTaBort.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.setBackground(Color.gray);
    }//GEN-LAST:event_imageLabelTaBortMouseMoved

    private void imageLabelÖkaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelÖkaMouseMoved
        imageLabelÖka.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.setBackground(Color.gray);
    }//GEN-LAST:event_imageLabelÖkaMouseMoved

    private void imageLabelMinskaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMinskaMouseMoved
        imageLabelMinska.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.setBackground(Color.gray);
    }//GEN-LAST:event_imageLabelMinskaMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        this.setBackground(Color.gray);
    }//GEN-LAST:event_formMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(Color.lightGray);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.ImageLabel imageLabelMinska;
    private imat.ImageLabel imageLabelTaBort;
    private imat.ImageLabel imageLabelÖka;
    private javax.swing.JLabel jLabelAntal;
    private javax.swing.JLabel jLabelPris;
    private javax.swing.JLabel jLabelProduktnamn;
    // End of variables declaration//GEN-END:variables
}
